plugins {
    id 'com.android.application'
}

android {
    namespace 'karacken.curleffect'
    compileSdk 37

    defaultConfig {
        applicationId 'karacken.curleffect'
        minSdk 24
        targetSdk 37
        versionCode 3
        versionName '1.1.2'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation project(':karackencurllib')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    testImplementation 'junit:junit:4.13.2'
}
